<?php

namespace Core\AccountingBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChartdetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChartdetailsRepository extends EntityRepository
{
	public function findAllBudgets()
	{
		return $this->getEntityManager()
			->createQuery(
					'SELECT b
					FROM CoreAccountingBundle:Chartdetails a
					JOIN CoreAccountingBundle:Chartmaster b
					GROUP BY b.accountcode, b.accountname
					ORDER BY b.accountcode ASC'
			)->getResult();
	}
	
	public function findBudgetbyid($id)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT b
				FROM CoreAccountingBundle:Chartdetails a
				JOIN CoreAccountingBundle:Chartmaster b
				WHERE b.accountcode = :id
				GROUP BY b.accountcode, b.accountname
				ORDER BY b.accountcode ASC'
		)->setParameter('id', $id)
		->getResult();
	}
}
