<?php

namespace Core\AccountingBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PeriodsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodsRepository extends EntityRepository
{
	public function findperiodnowithlastdateinperiod($date)
	{
		$id = $date->format('Y-m-t');
		return $this->getEntityManager()
		->createQuery(
				'SELECT a.lastdateinperiod
				FROM CoreAccountingBundle:Periods a
				WHERE a.periodno = :id'
		)->setParameter('id', $id)
		->getResult();
	}
	
}
