CoreAccountingBundle_homepage:
    pattern:  /accounting/index
    defaults: { _controller: CoreAccountingBundle:Page:index }
    requirements:
        _method:  GET

CoreAccountingBundle_transactions:
    pattern:  /accounting/transactions
    defaults: { _controller: CoreAccountingBundle:Page:transactions }
    requirements:
        _method:  GET




    
CoreAccountingBundle_transactions_single:
    pattern:  /accounting/transactions/single
    defaults: { _controller: CoreAccountingBundle:Transactions:single }
    
CoreAccountingBundle_transactions_batch:
    pattern:  /accounting/transactions/batch
    defaults: { _controller: CoreAccountingBundle:Transactions:batch }







CoreAccountingBundle_maintenance:
    pattern:  /accounting/maintenance
    defaults: { _controller: CoreAccountingBundle:Page:maintenance }



    
CoreAccountingBundle_maintenance_importdefinitions:
    pattern:  /accounting/maintenance/importdefinitions
    defaults: { _controller: CoreAccountingBundle:Maintenance:index }
    
CoreAccountingBundle_maintenance_importdefinitions_create:
    pattern:  /accounting/maintenance/importdefinitions
    defaults: { _controller: CoreAccountingBundle:Maintenance:index }
    
CoreAccountingBundle_maintenance_importdefinitions_edit:
    pattern:  /accounting/maintenance/importdefinitions
    defaults: { _controller: CoreAccountingBundle:Maintenance:index }
    
CoreAccountingBundle_maintenance_importdefinitions_delete:
    pattern:  /accounting/maintenance/importdefinitions
    defaults: { _controller: CoreAccountingBundle:Maintenance:index }
    
    
CoreAccountingBundle_maintenance_chartofaccounts:
    pattern:  /accounting/maintenance/chartofaccounts
    defaults: { _controller: CoreAccountingBundle:Maintenance:index }
    