CoreAccountingBundle_homepage:
    pattern:  /accounting/index
    defaults: { _controller: CoreAccountingBundle:Page:index }
    requirements:
        _method:  GET

CoreAccountingBundle_transactions:
    pattern:  /accounting/transactions
    defaults: { _controller: CoreAccountingBundle:Page:transactions }
    requirements:
        _method:  GET







CoreAccountingBundle_maintenance_chartmaster_show:
    pattern:	/accounting/maintenance/chartmaster
    defaults:	{ _controller:CoreAccountingBundle:Maintenance:showchartmaster }
    requirements:
        _method:  GET

CoreAccountingBundle_maintenance_chartmaster_edit:
    pattern:	/accounting/maintenance/chartmaster/edit/{account_id}
    defaults:	{ _controller:CoreAccountingBundle:Maintenance:editchartmaster }
    requirements:
        _method:  GET

CoreAccountingBundle_maintenance_chartmaster_delete:
    pattern:	/accounting/maintenance/chartmaster/delete/{account_id}
    defaults:	{ _controller:CoreAccountingBundle:Maintenance:deletechartmaster }
    requirements:
        _method:  GET










CoreAccountingBundle_test:
    pattern:  /accounting/test
    defaults: { _controller: CoreAccountingBundle:Page:test }
    requirements:
        _method:  GET



    
CoreAccountingBundle_transactions_single:
    pattern:  /accounting/transactions/single
    defaults: { _controller: CoreAccountingBundle:Transactions:single }
    
CoreAccountingBundle_transactions_batch:
    pattern:  /accounting/transactions/batch
    defaults: { _controller: CoreAccountingBundle:Transactions:batch }







CoreAccountingBundle_maintenance:
    pattern:  /accounting/maintenance
    defaults: { _controller: CoreAccountingBundle:Page:maintenance }



    
CoreAccountingBundle_maintenance_importdefinitions:
    pattern:  /accounting/maintenance/importdefinitions
    defaults: { _controller: CoreAccountingBundle:Maintenance:index }
    
CoreAccountingBundle_maintenance_importdefinitions_create:
    pattern:  /accounting/maintenance/importdefinitions
    defaults: { _controller: CoreAccountingBundle:Maintenance:index }
    
CoreAccountingBundle_maintenance_importdefinitions_edit:
    pattern:  /accounting/maintenance/importdefinitions
    defaults: { _controller: CoreAccountingBundle:Maintenance:index }
    
CoreAccountingBundle_maintenance_importdefinitions_delete:
    pattern:  /accounting/maintenance/importdefinitions
    defaults: { _controller: CoreAccountingBundle:Maintenance:index }
    
    
CoreAccountingBundle_maintenance_chartofaccounts:
    pattern:  /accounting/maintenance/chartofaccounts
    defaults: { _controller: CoreAccountingBundle:Maintenance:index }
    