# Top
CoreAccountingBundle_home:
    pattern:  /
    defaults: { _controller: CoreAccountingBundle:Default:index }
    requirements:
        _method:  GET

## Accounting app
CoreAccountingBundle_accounting_home:
    pattern:  /accounting/index
    defaults: { _controller: CoreAccountingBundle:Default:accounting }
    requirements:
        _method:  GET

### Accounting Transactions



### Accounting Tools



### Accounting Maintenance

#### Chart of Accounts
CoreAccountingBundle_maintenance_chartmaster_show:
    pattern:	/accounting/maintenance/chartmaster
    defaults:	{ _controller:CoreAccountingBundle:Maintenance:showchartmaster }
    requirements:
        _method:  GET

CoreAccountingBundle_maintenance_chartmaster_add:
    pattern:	/accounting/maintenance/chartmaster/add
    defaults:	{ _controller:CoreAccountingBundle:Maintenance:addchartmaster }
    requirements:
        _method:  GET|POST

CoreAccountingBundle_maintenance_chartmaster_edit:
    pattern:	/accounting/maintenance/chartmaster/edit/{account_id}
    defaults:	{ _controller:CoreAccountingBundle:Maintenance:editchartmaster }
    requirements:
        _method:  GET|POST

CoreAccountingBundle_maintenance_chartmaster_delete:
    pattern:	/accounting/maintenance/chartmaster/delete/{account_id}
    defaults:	{ _controller:CoreAccountingBundle:Maintenance:deletechartmaster }
    requirements:
        _method:  GET|POST

#### Periods
CoreAccountingBundle_maintenance_periods_show:
    pattern:	/accounting/maintenance/periods
    defaults:	{ _controller:CoreAccountingBundle:Maintenance:showperiods }
    requirements:
        _method:  GET

CoreAccountingBundle_maintenance_periods_add:
    pattern:	/accounting/maintenance/periods/add
    defaults:	{ _controller:CoreAccountingBundle:Maintenance:addperiods }
    requirements:
        _method:  GET|POST

CoreAccountingBundle_maintenance_periods_edit:
    pattern:	/accounting/maintenance/periods/edit/{period_id}
    defaults:	{ _controller:CoreAccountingBundle:Maintenance:editperiods }
    requirements:
        _method:  GET|POST

CoreAccountingBundle_maintenance_periods_delete:
    pattern:	/accounting/maintenance/periods/delete/{period_id}
    defaults:	{ _controller:CoreAccountingBundle:Maintenance:deleteperiods }
    requirements:
        _method:  GET


#### Budget


#### Tags


#### Import Transaction Definitions



### Accounting Reports


## Investments app
CoreAccountingBundle_investments_home:
    pattern:  /investments/index
    defaults: { _controller: CoreAccountingBundle:Default:investments }
    requirements:
        _method:  GET

## Assets app
CoreAccountingBundle_assets_home:
    pattern:  /assets/index
    defaults: { _controller: CoreAccountingBundle:Default:assets }
    requirements:
        _method:  GET



    