# Top
CoreAccountingBundle_home:
    pattern:  /
    defaults: { _controller: CoreAccountingBundle:Default:index }
    requirements:
        _method:  GET

## Accounting app
CoreAccountingBundle_accounting_home:
    pattern:  /accounting/index
    defaults: { _controller: CoreAccountingBundle:Default:accounting }
    requirements:
        _method:  GET

### Accounting Transactions



### Accounting Tools



### Accounting Maintenance

#### Chart of Accounts
CoreAccountingBundle_maintenance_chartmaster_show:
    pattern:	/accounting/maintenance/chartmaster
    defaults:	{ _controller:CoreAccountingBundle:Maintenance:showchartmaster }
    requirements:
        _method:  GET

CoreAccountingBundle_maintenance_chartmaster_add:
    pattern:	/accounting/maintenance/chartmaster/add
    defaults:	{ _controller:CoreAccountingBundle:Maintenance:addchartmaster }
    requirements:
        _method:  GET|POST

CoreAccountingBundle_maintenance_chartmaster_edit:
    pattern:	/accounting/maintenance/chartmaster/edit/{account_id}
    defaults:	{ _controller:CoreAccountingBundle:Maintenance:editchartmaster }
    requirements:
        _method:  GET|POST

CoreAccountingBundle_maintenance_chartmaster_delete:
    pattern:	/accounting/maintenance/chartmaster/delete/{account_id}
    defaults:	{ _controller:CoreAccountingBundle:Maintenance:deletechartmaster }
    requirements:
        _method:  GET|POST

#### Account Sections

#### Account Group
CoreAccountingBundle_maintenance_accountgroups_show:
    pattern:	/accounting/maintenance/accountgroups
    defaults:	{ _controller:CoreAccountingBundle:Maintenance:showaccountgroups }
    requirements:
        _method:  GET

CoreAccountingBundle_maintenance_accountgroups_add:
    pattern:	/accounting/maintenance/accountgroups/add
    defaults:	{ _controller:CoreAccountingBundle:Maintenance:addaccountgroups }
    requirements:
        _method:  GET|POST

CoreAccountingBundle_maintenance_accountgroups_edit:
    pattern:	/accounting/maintenance/accountgroups/edit/{group_id}
    defaults:	{ _controller:CoreAccountingBundle:Maintenance:editaccountgroups }
    requirements:
        _method:  GET|POST

CoreAccountingBundle_maintenance_accountgroups_delete:
    pattern:	/accounting/maintenance/accountgroups/delete/{group_id}
    defaults:	{ _controller:CoreAccountingBundle:Maintenance:deleteaccountgroups }
    requirements:
        _method:  GET|POST

#### Periods



#### Budget


#### Tags


#### Import Transaction Definitions



### Accounting Reports


## Investments app
CoreAccountingBundle_investments_home:
    pattern:  /investments/index
    defaults: { _controller: CoreAccountingBundle:Default:investments }
    requirements:
        _method:  GET

## Assets app
CoreAccountingBundle_assets_home:
    pattern:  /assets/index
    defaults: { _controller: CoreAccountingBundle:Default:assets }
    requirements:
        _method:  GET



    