# src/Core/BlogBundle/Resources/config/routing.yml
CoreBlogBundle_homepage:
    pattern: /index
    defaults: { _controller: CoreBlogBundle:Page:index }
    requirements:
        _method:  GET

CoreBlogBundle_about:
    pattern: /about
    defaults: { _controller: CoreBlogBundle:Page:about }
    requirements:
        _method:  GET

CoreBlogBundle_contact:
    pattern:  /contact
    defaults: { _controller: CoreBlogBundle:Page:contact }
    requirements:
        _method:  GET|POST

CoreBlogBundle_blog_show:
    pattern:  /{id}
    defaults: { _controller: CoreBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+
        
CoreBlogBundle_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: CoreBlogBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+